/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_andrefloresr;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andre
 */
public class Tienda extends javax.swing.JFrame {

    /**
     * Creates new form Tienda
     */
    public Tienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paginaConsola = new javax.swing.JDialog();
        labelFabricante = new javax.swing.JLabel();
        textfieldFabricante = new javax.swing.JTextField();
        labelanios = new javax.swing.JLabel();
        textfieldAnios = new javax.swing.JTextField();
        labelprecio = new javax.swing.JLabel();
        textfieldPrecio = new javax.swing.JTextField();
        labelmodelo = new javax.swing.JLabel();
        textfieldModelo = new javax.swing.JTextField();
        labeltipo = new javax.swing.JLabel();
        radiobotonPortatil = new javax.swing.JRadioButton();
        radiobotonEstacionaria = new javax.swing.JRadioButton();
        botonCrearConsola = new javax.swing.JButton();
        labelIdentificacion = new javax.swing.JLabel();
        textfieldIdentificacion = new javax.swing.JTextField();
        botonesTipoConsola = new javax.swing.ButtonGroup();
        paginaPortatil = new javax.swing.JDialog();
        labelTamanioPantalla = new javax.swing.JLabel();
        labelDuracionBateria = new javax.swing.JLabel();
        labelEstuche = new javax.swing.JLabel();
        rb_SiEstuche = new javax.swing.JRadioButton();
        rb_NoEstuche = new javax.swing.JRadioButton();
        rb_pequenio = new javax.swing.JRadioButton();
        rb_mediano = new javax.swing.JRadioButton();
        rb_grande = new javax.swing.JRadioButton();
        textfieldBateria = new javax.swing.JTextField();
        botonTerminarPortatil = new javax.swing.JButton();
        paginaestacionaria = new javax.swing.JDialog();
        labelNumControles = new javax.swing.JLabel();
        textfieldNumControles = new javax.swing.JTextField();
        LabelAlmacenamiento = new javax.swing.JLabel();
        textfieldAlmacenamiento = new javax.swing.JTextField();
        labelTipoConexion = new javax.swing.JLabel();
        textfieldTipoConexion = new javax.swing.JTextField();
        botonestacionaria = new javax.swing.JButton();
        botonesEstuche = new javax.swing.ButtonGroup();
        botonesTamanio = new javax.swing.ButtonGroup();
        popupmenuConsola = new javax.swing.JPopupMenu();
        menuitemEliminar = new javax.swing.JMenuItem();
        menuitemModificar = new javax.swing.JMenuItem();
        menuitemVerJuegos = new javax.swing.JMenuItem();
        paginaModificar = new javax.swing.JDialog();
        labelFabricante1 = new javax.swing.JLabel();
        textfieldFabricante1 = new javax.swing.JTextField();
        labelanios1 = new javax.swing.JLabel();
        textfieldAnios1 = new javax.swing.JTextField();
        labelprecio1 = new javax.swing.JLabel();
        textfieldPrecio1 = new javax.swing.JTextField();
        labelmodelo1 = new javax.swing.JLabel();
        textfieldModelo1 = new javax.swing.JTextField();
        labeltipo1 = new javax.swing.JLabel();
        radiobotonPortatil1 = new javax.swing.JRadioButton();
        radiobotonEstacionaria1 = new javax.swing.JRadioButton();
        botonCrearConsola1 = new javax.swing.JButton();
        labelIdentificacion1 = new javax.swing.JLabel();
        textfieldIdentificacion1 = new javax.swing.JTextField();
        grupotipo1 = new javax.swing.ButtonGroup();
        modificarportatil = new javax.swing.JDialog();
        labelTamanioPantalla1 = new javax.swing.JLabel();
        labelDuracionBateria1 = new javax.swing.JLabel();
        labelEstuche1 = new javax.swing.JLabel();
        rb_SiEstuche1 = new javax.swing.JRadioButton();
        rb_NoEstuche1 = new javax.swing.JRadioButton();
        rb_pequenio1 = new javax.swing.JRadioButton();
        rb_mediano1 = new javax.swing.JRadioButton();
        rb_grande1 = new javax.swing.JRadioButton();
        textfieldBateria1 = new javax.swing.JTextField();
        botonTerminarPortatil1 = new javax.swing.JButton();
        grupoModifEstuche = new javax.swing.ButtonGroup();
        grupoModifTamanio = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaConsolas = new javax.swing.JTable();
        botonAgregarConsola = new javax.swing.JButton();

        labelFabricante.setText("Fabricante");

        labelanios.setText("Anios de uso");

        labelprecio.setText("Precio");

        labelmodelo.setText("Modelo");

        labeltipo.setText("Tipo");

        botonesTipoConsola.add(radiobotonPortatil);
        radiobotonPortatil.setText("Portatil");

        botonesTipoConsola.add(radiobotonEstacionaria);
        radiobotonEstacionaria.setText("Estacionaria");
        radiobotonEstacionaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobotonEstacionariaActionPerformed(evt);
            }
        });

        botonCrearConsola.setText("Crear consola");
        botonCrearConsola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCrearConsolaMouseClicked(evt);
            }
        });

        labelIdentificacion.setText("Identificacion");

        textfieldIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldIdentificacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paginaConsolaLayout = new javax.swing.GroupLayout(paginaConsola.getContentPane());
        paginaConsola.getContentPane().setLayout(paginaConsolaLayout);
        paginaConsolaLayout.setHorizontalGroup(
            paginaConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaConsolaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(paginaConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paginaConsolaLayout.createSequentialGroup()
                        .addComponent(labelIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paginaConsolaLayout.createSequentialGroup()
                        .addGroup(paginaConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labeltipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelanios, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 26, Short.MAX_VALUE)
                        .addGroup(paginaConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(textfieldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldAnios, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radiobotonPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(radiobotonEstacionaria, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(botonCrearConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        paginaConsolaLayout.setVerticalGroup(
            paginaConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaConsolaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(paginaConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelIdentificacion)
                    .addComponent(textfieldIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paginaConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFabricante)
                    .addComponent(textfieldFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paginaConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelanios)
                    .addComponent(textfieldAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(paginaConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelprecio)
                    .addComponent(textfieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(paginaConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelmodelo)
                    .addComponent(textfieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(paginaConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeltipo)
                    .addComponent(radiobotonPortatil)
                    .addComponent(radiobotonEstacionaria))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paginaConsolaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCrearConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        labelTamanioPantalla.setText("tamanio de la pantalla");

        labelDuracionBateria.setText("Duracion de la bateria");

        labelEstuche.setText("Lleva estuche?");

        botonesEstuche.add(rb_SiEstuche);
        rb_SiEstuche.setText("Si");
        rb_SiEstuche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_SiEstucheActionPerformed(evt);
            }
        });

        botonesEstuche.add(rb_NoEstuche);
        rb_NoEstuche.setText("No");
        rb_NoEstuche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_NoEstucheActionPerformed(evt);
            }
        });

        rb_pequenio.setText("pequenio");

        rb_mediano.setText("mediano");

        rb_grande.setText("grande");
        rb_grande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_grandeActionPerformed(evt);
            }
        });

        textfieldBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldBateriaActionPerformed(evt);
            }
        });

        botonTerminarPortatil.setText("Finalizar Creacion");
        botonTerminarPortatil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTerminarPortatilMouseClicked(evt);
            }
        });
        botonTerminarPortatil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarPortatilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paginaPortatilLayout = new javax.swing.GroupLayout(paginaPortatil.getContentPane());
        paginaPortatil.getContentPane().setLayout(paginaPortatilLayout);
        paginaPortatilLayout.setHorizontalGroup(
            paginaPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaPortatilLayout.createSequentialGroup()
                .addGroup(paginaPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paginaPortatilLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(botonTerminarPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paginaPortatilLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(paginaPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paginaPortatilLayout.createSequentialGroup()
                                .addComponent(labelEstuche)
                                .addGap(18, 18, 18)
                                .addComponent(rb_SiEstuche, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_NoEstuche, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paginaPortatilLayout.createSequentialGroup()
                                .addGroup(paginaPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelDuracionBateria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTamanioPantalla, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(paginaPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paginaPortatilLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb_pequenio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(rb_mediano, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_grande, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(paginaPortatilLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(textfieldBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        paginaPortatilLayout.setVerticalGroup(
            paginaPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaPortatilLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(paginaPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTamanioPantalla)
                    .addComponent(rb_pequenio)
                    .addComponent(rb_mediano)
                    .addComponent(rb_grande))
                .addGap(54, 54, 54)
                .addGroup(paginaPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuracionBateria)
                    .addComponent(textfieldBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(paginaPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstuche)
                    .addComponent(rb_SiEstuche)
                    .addComponent(rb_NoEstuche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(botonTerminarPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        labelNumControles.setText("Numero de controles");

        textfieldNumControles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNumControlesActionPerformed(evt);
            }
        });

        LabelAlmacenamiento.setText("Almacenamiento de la consola");

        textfieldAlmacenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldAlmacenamientoActionPerformed(evt);
            }
        });

        labelTipoConexion.setText("Tipo de conexion");

        textfieldTipoConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldTipoConexionActionPerformed(evt);
            }
        });

        botonestacionaria.setText("Finalizar Creacion");
        botonestacionaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonestacionariaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paginaestacionariaLayout = new javax.swing.GroupLayout(paginaestacionaria.getContentPane());
        paginaestacionaria.getContentPane().setLayout(paginaestacionariaLayout);
        paginaestacionariaLayout.setHorizontalGroup(
            paginaestacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaestacionariaLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(paginaestacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNumControles)
                    .addComponent(LabelAlmacenamiento)
                    .addComponent(labelTipoConexion))
                .addGap(18, 18, 18)
                .addGroup(paginaestacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textfieldTipoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldAlmacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldNumControles, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paginaestacionariaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonestacionaria)
                .addGap(15, 15, 15))
        );
        paginaestacionariaLayout.setVerticalGroup(
            paginaestacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaestacionariaLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(paginaestacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumControles)
                    .addComponent(textfieldNumControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(paginaestacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAlmacenamiento)
                    .addComponent(textfieldAlmacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(paginaestacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTipoConexion)
                    .addComponent(textfieldTipoConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(botonestacionaria, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuitemEliminar.setText("Eliminar");
        menuitemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemEliminarActionPerformed(evt);
            }
        });
        popupmenuConsola.add(menuitemEliminar);

        menuitemModificar.setText("Modificar");
        menuitemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemModificarActionPerformed(evt);
            }
        });
        popupmenuConsola.add(menuitemModificar);

        menuitemVerJuegos.setText("jMenuItem1");
        popupmenuConsola.add(menuitemVerJuegos);

        labelFabricante1.setText("Fabricante");

        labelanios1.setText("Anios de uso");

        labelprecio1.setText("Precio");

        labelmodelo1.setText("Modelo");

        labeltipo1.setText("Tipo");

        grupotipo1.add(radiobotonPortatil1);
        radiobotonPortatil1.setText("Portatil");

        grupotipo1.add(radiobotonEstacionaria1);
        radiobotonEstacionaria1.setText("Estacionaria");
        radiobotonEstacionaria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobotonEstacionaria1ActionPerformed(evt);
            }
        });

        botonCrearConsola1.setText("Modificar Consola");
        botonCrearConsola1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCrearConsola1MouseClicked(evt);
            }
        });

        labelIdentificacion1.setText("Identificacion");

        textfieldIdentificacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldIdentificacion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paginaModificarLayout = new javax.swing.GroupLayout(paginaModificar.getContentPane());
        paginaModificar.getContentPane().setLayout(paginaModificarLayout);
        paginaModificarLayout.setHorizontalGroup(
            paginaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaModificarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(paginaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paginaModificarLayout.createSequentialGroup()
                        .addComponent(labelIdentificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paginaModificarLayout.createSequentialGroup()
                        .addGroup(paginaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labeltipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelmodelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelprecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelanios1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFabricante1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 26, Short.MAX_VALUE)
                        .addGroup(paginaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(textfieldFabricante1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldAnios1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radiobotonPortatil1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldIdentificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(radiobotonEstacionaria1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(botonCrearConsola1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        paginaModificarLayout.setVerticalGroup(
            paginaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaModificarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(paginaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelIdentificacion1)
                    .addComponent(textfieldIdentificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paginaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFabricante1)
                    .addComponent(textfieldFabricante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paginaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelanios1)
                    .addComponent(textfieldAnios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(paginaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelprecio1)
                    .addComponent(textfieldPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(paginaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelmodelo1)
                    .addComponent(textfieldModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(paginaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeltipo1)
                    .addComponent(radiobotonPortatil1)
                    .addComponent(radiobotonEstacionaria1))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paginaModificarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCrearConsola1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        labelTamanioPantalla1.setText("tamanio de la pantalla");

        labelDuracionBateria1.setText("Duracion de la bateria");

        labelEstuche1.setText("Lleva estuche?");

        grupoModifEstuche.add(rb_SiEstuche1);
        rb_SiEstuche1.setText("Si");
        rb_SiEstuche1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_SiEstuche1ActionPerformed(evt);
            }
        });

        grupoModifEstuche.add(rb_NoEstuche1);
        rb_NoEstuche1.setText("No");
        rb_NoEstuche1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_NoEstuche1ActionPerformed(evt);
            }
        });

        grupoModifTamanio.add(rb_pequenio1);
        rb_pequenio1.setText("pequenio");

        grupoModifTamanio.add(rb_mediano1);
        rb_mediano1.setText("mediano");

        grupoModifTamanio.add(rb_grande1);
        rb_grande1.setText("grande");
        rb_grande1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_grande1ActionPerformed(evt);
            }
        });

        textfieldBateria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldBateria1ActionPerformed(evt);
            }
        });

        botonTerminarPortatil1.setText("Finalizar Modificacion");
        botonTerminarPortatil1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTerminarPortatil1MouseClicked(evt);
            }
        });
        botonTerminarPortatil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTerminarPortatil1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modificarportatilLayout = new javax.swing.GroupLayout(modificarportatil.getContentPane());
        modificarportatil.getContentPane().setLayout(modificarportatilLayout);
        modificarportatilLayout.setHorizontalGroup(
            modificarportatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarportatilLayout.createSequentialGroup()
                .addGroup(modificarportatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarportatilLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(botonTerminarPortatil1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modificarportatilLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(modificarportatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modificarportatilLayout.createSequentialGroup()
                                .addComponent(labelEstuche1)
                                .addGap(18, 18, 18)
                                .addComponent(rb_SiEstuche1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_NoEstuche1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(modificarportatilLayout.createSequentialGroup()
                                .addGroup(modificarportatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelDuracionBateria1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTamanioPantalla1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(modificarportatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(modificarportatilLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb_pequenio1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(rb_mediano1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_grande1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(modificarportatilLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(textfieldBateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        modificarportatilLayout.setVerticalGroup(
            modificarportatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarportatilLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(modificarportatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTamanioPantalla1)
                    .addComponent(rb_pequenio1)
                    .addComponent(rb_mediano1)
                    .addComponent(rb_grande1))
                .addGap(54, 54, 54)
                .addGroup(modificarportatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuracionBateria1)
                    .addComponent(textfieldBateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(modificarportatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstuche1)
                    .addComponent(rb_SiEstuche1)
                    .addComponent(rb_NoEstuche1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(botonTerminarPortatil1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaConsolas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Fabricante", "Anios de uso", "Precio", "Modelo", "Tipo", "Tamanio ", "Duracion bateria", "Estuche", "numero de controles", "almacenamiento", "tipo de conexion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaConsolas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaConsolasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaConsolas);

        botonAgregarConsola.setText("Agregar Consola");
        botonAgregarConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarConsolaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(botonAgregarConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(botonAgregarConsola, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarConsolaActionPerformed
        crearConsola();
    }//GEN-LAST:event_botonAgregarConsolaActionPerformed

    private void radiobotonEstacionariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobotonEstacionariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobotonEstacionariaActionPerformed

    private void botonCrearConsolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearConsolaMouseClicked
        String identificacion;
        String fabricante;
        int aniosuso;
        double precio;
        String modelo;
        identificacion = textfieldIdentificacion.getText();
        fabricante = textfieldFabricante.getText();
        aniosuso = Integer.parseInt(textfieldAnios.getText());
        precio = Double.parseDouble(textfieldPrecio.getText());
        modelo = textfieldModelo.getText();
        if (radiobotonPortatil.isSelected()) {
            paginaportatil();
        } else {
            paginaestacionaria();
        }

    }//GEN-LAST:event_botonCrearConsolaMouseClicked

    private void rb_SiEstucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_SiEstucheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_SiEstucheActionPerformed

    private void rb_NoEstucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_NoEstucheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_NoEstucheActionPerformed

    private void rb_grandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_grandeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_grandeActionPerformed

    private void textfieldBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldBateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldBateriaActionPerformed

    private void botonTerminarPortatilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarPortatilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTerminarPortatilActionPerformed

    private void botonTerminarPortatilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTerminarPortatilMouseClicked
        DefaultTableModel modelotabla = (DefaultTableModel) TablaConsolas.getModel();
        String tamanio = "";
        boolean estuche = false;
        String identificacion = "";
        String fabricante;
        int aniosuso;
        double precio;
        String modelo;
        identificacion = textfieldIdentificacion.getText();
        fabricante = textfieldFabricante.getText();
        aniosuso = Integer.parseInt(textfieldAnios.getText());
        precio = Double.parseDouble(textfieldPrecio.getText());
        modelo = textfieldModelo.getText();
        int duracionBateria;
        if (rb_pequenio.isSelected()) {
            tamanio = "pequenio";
        } else if (rb_mediano.isSelected()) {
            tamanio = "mediano";
        } else if (rb_grande.isSelected()) {
            tamanio = "grande";
        }
        duracionBateria = Integer.parseInt(textfieldBateria.getText());
        if (rb_SiEstuche.isSelected()) {
            estuche = true;
        } else {
            estuche = false;
        }
        portatil p = new portatil(tamanio, duracionBateria, estuche, identificacion, fabricante, aniosuso, precio, modelo);
        Object[] fila = {identificacion, fabricante, aniosuso, precio, modelo, "portatil", tamanio, duracionBateria, estuche};
        modelotabla.addRow(fila);
        TablaConsolas.setModel(modelotabla);
        consolas.add(p);
    }//GEN-LAST:event_botonTerminarPortatilMouseClicked

    private void textfieldIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldIdentificacionActionPerformed

    private void textfieldNumControlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNumControlesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNumControlesActionPerformed

    private void textfieldAlmacenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldAlmacenamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldAlmacenamientoActionPerformed

    private void textfieldTipoConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldTipoConexionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldTipoConexionActionPerformed

    private void botonestacionariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonestacionariaActionPerformed
        DefaultTableModel modelotabla = (DefaultTableModel) TablaConsolas.getModel();
        String identificacion = "";
        String fabricante;
        int aniosuso;
        double precio;
        String modelo;
        identificacion = textfieldIdentificacion.getText();
        fabricante = textfieldFabricante.getText();
        aniosuso = Integer.parseInt(textfieldAnios.getText());
        precio = Double.parseDouble(textfieldPrecio.getText());
        modelo = textfieldModelo.getText();
        int numControles;
        int almacenamiento;
        String tipoConexion;
        numControles = Integer.parseInt(textfieldNumControles.getText());
        almacenamiento = Integer.parseInt(textfieldAlmacenamiento.getText());
        tipoConexion = textfieldTipoConexion.getText();
        estacionaria e = new estacionaria(numControles, almacenamiento, tipoConexion, identificacion, fabricante, aniosuso, precio, modelo);
        Object[] fila = {identificacion, fabricante, aniosuso, precio, modelo, "Estacionaria", null, null, null, numControles, almacenamiento, tipoConexion};
        modelotabla.addRow(fila);
        TablaConsolas.setModel(modelotabla);
    }//GEN-LAST:event_botonestacionariaActionPerformed

    private void TablaConsolasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaConsolasMouseClicked

        if (TablaConsolas.getSelectedRow() >= 0) {
            if (evt.isMetaDown()) {
                popupmenuConsola.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_TablaConsolasMouseClicked

    private void menuitemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemEliminarActionPerformed
        int response = JOptionPane.showConfirmDialog(
                this,
                "Seguro de Eliminar?",
                "Confirm",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.OK_OPTION) {
            DefaultTableModel m
                    = (DefaultTableModel) TablaConsolas.getModel();
            m.removeRow(TablaConsolas.getSelectedRow());
            TablaConsolas.setModel(m);
        }
    }//GEN-LAST:event_menuitemEliminarActionPerformed

    private void menuitemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemModificarActionPerformed
        paginamodificar();
    }//GEN-LAST:event_menuitemModificarActionPerformed

    private void radiobotonEstacionaria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobotonEstacionaria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiobotonEstacionaria1ActionPerformed

    private void botonCrearConsola1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearConsola1MouseClicked
        String identificacion;
        String fabricante;
        int aniosuso;
        double precio;
        String modelo;
        identificacion = textfieldIdentificacion1.getText();
        fabricante = textfieldFabricante1.getText();
        aniosuso = Integer.parseInt(textfieldAnios1.getText());
        precio = Double.parseDouble(textfieldPrecio1.getText());
        modelo = textfieldModelo1.getText();
        if (radiobotonPortatil1.isSelected()) {
            modificarportatil();
        } else {

        }
    }//GEN-LAST:event_botonCrearConsola1MouseClicked

    private void textfieldIdentificacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldIdentificacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldIdentificacion1ActionPerformed

    private void rb_SiEstuche1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_SiEstuche1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_SiEstuche1ActionPerformed

    private void rb_NoEstuche1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_NoEstuche1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_NoEstuche1ActionPerformed

    private void rb_grande1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_grande1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_grande1ActionPerformed

    private void textfieldBateria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldBateria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldBateria1ActionPerformed

    private void botonTerminarPortatil1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTerminarPortatil1MouseClicked
        DefaultTableModel modelotabla = (DefaultTableModel) TablaConsolas.getModel();
        String tamanio = "";
        boolean estuche = false;
        String identificacion = "";
        String fabricante;
        int aniosuso;
        double precio;
        String modelo;
        identificacion = textfieldIdentificacion1.getText();
        fabricante = textfieldFabricante1.getText();
        aniosuso = Integer.parseInt(textfieldAnios1.getText());
        precio = Double.parseDouble(textfieldPrecio1.getText());
        modelo = textfieldModelo1.getText();
        int duracionBateria;
        if (rb_pequenio1.isSelected()) {
            tamanio = "pequenio";
        } else if (rb_mediano1.isSelected()) {
            tamanio = "mediano";
        } else if (rb_grande1.isSelected()) {
            tamanio = "grande";
        }
        duracionBateria = Integer.parseInt(textfieldBateria1.getText());
        if (rb_SiEstuche1.isSelected()) {
            estuche = true;
        } else {
            estuche = false;
        }
        portatil p;
        p = (portatil) consolas.get(TablaConsolas.getSelectedRow());
        p.setIdentificacion(identificacion);
        p.setAniosDeUso(aniosuso);
        p.setBateria(duracionBateria);
        p.setEstuche(estuche);
        p.setTamPantalla(tamanio);
        p.setModelo(modelo);
        p.setPrecio(precio);
        p.setFabricante(fabricante);
        consolas.set(TablaConsolas.getSelectedRow(), p);
        
        TablaConsolas.setModel(modelotabla);
    }//GEN-LAST:event_botonTerminarPortatil1MouseClicked

    private void botonTerminarPortatil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTerminarPortatil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTerminarPortatil1ActionPerformed

    private void crearConsola() {
        paginaConsola.pack();
        paginaConsola.setModal(true);
        paginaConsola.setLocationRelativeTo(this);
        paginaConsola.setVisible(true);
    }

    private void paginaportatil() {
        paginaPortatil.pack();
        paginaPortatil.setModal(true);
        paginaPortatil.setLocationRelativeTo(this);
        paginaPortatil.setVisible(true);
    }

    private void paginaestacionaria() {
        paginaestacionaria.pack();
        paginaestacionaria.setModal(true);
        paginaestacionaria.setLocationRelativeTo(this);
        paginaestacionaria.setVisible(true);
    }

    private void paginamodificar() {
        paginaModificar.pack();
        paginaModificar.setModal(true);
        paginaModificar.setLocationRelativeTo(this);
        paginaModificar.setVisible(true);
    }

    private void modificarportatil() {
        modificarportatil.pack();
        modificarportatil.setModal(true);
        modificarportatil.setLocationRelativeTo(this);
        modificarportatil.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienda().setVisible(true);
            }
        });
    }
    ArrayList<consola> consolas = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAlmacenamiento;
    private javax.swing.JTable TablaConsolas;
    private javax.swing.JButton botonAgregarConsola;
    private javax.swing.JButton botonCrearConsola;
    private javax.swing.JButton botonCrearConsola1;
    private javax.swing.JButton botonTerminarPortatil;
    private javax.swing.JButton botonTerminarPortatil1;
    private javax.swing.ButtonGroup botonesEstuche;
    private javax.swing.ButtonGroup botonesTamanio;
    private javax.swing.ButtonGroup botonesTipoConsola;
    private javax.swing.JButton botonestacionaria;
    private javax.swing.ButtonGroup grupoModifEstuche;
    private javax.swing.ButtonGroup grupoModifTamanio;
    private javax.swing.ButtonGroup grupotipo1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDuracionBateria;
    private javax.swing.JLabel labelDuracionBateria1;
    private javax.swing.JLabel labelEstuche;
    private javax.swing.JLabel labelEstuche1;
    private javax.swing.JLabel labelFabricante;
    private javax.swing.JLabel labelFabricante1;
    private javax.swing.JLabel labelIdentificacion;
    private javax.swing.JLabel labelIdentificacion1;
    private javax.swing.JLabel labelNumControles;
    private javax.swing.JLabel labelTamanioPantalla;
    private javax.swing.JLabel labelTamanioPantalla1;
    private javax.swing.JLabel labelTipoConexion;
    private javax.swing.JLabel labelanios;
    private javax.swing.JLabel labelanios1;
    private javax.swing.JLabel labelmodelo;
    private javax.swing.JLabel labelmodelo1;
    private javax.swing.JLabel labelprecio;
    private javax.swing.JLabel labelprecio1;
    private javax.swing.JLabel labeltipo;
    private javax.swing.JLabel labeltipo1;
    private javax.swing.JMenuItem menuitemEliminar;
    private javax.swing.JMenuItem menuitemModificar;
    private javax.swing.JMenuItem menuitemVerJuegos;
    private javax.swing.JDialog modificarportatil;
    private javax.swing.JDialog paginaConsola;
    private javax.swing.JDialog paginaModificar;
    private javax.swing.JDialog paginaPortatil;
    private javax.swing.JDialog paginaestacionaria;
    private javax.swing.JPopupMenu popupmenuConsola;
    private javax.swing.JRadioButton radiobotonEstacionaria;
    private javax.swing.JRadioButton radiobotonEstacionaria1;
    private javax.swing.JRadioButton radiobotonPortatil;
    private javax.swing.JRadioButton radiobotonPortatil1;
    private javax.swing.JRadioButton rb_NoEstuche;
    private javax.swing.JRadioButton rb_NoEstuche1;
    private javax.swing.JRadioButton rb_SiEstuche;
    private javax.swing.JRadioButton rb_SiEstuche1;
    private javax.swing.JRadioButton rb_grande;
    private javax.swing.JRadioButton rb_grande1;
    private javax.swing.JRadioButton rb_mediano;
    private javax.swing.JRadioButton rb_mediano1;
    private javax.swing.JRadioButton rb_pequenio;
    private javax.swing.JRadioButton rb_pequenio1;
    private javax.swing.JTextField textfieldAlmacenamiento;
    private javax.swing.JTextField textfieldAnios;
    private javax.swing.JTextField textfieldAnios1;
    private javax.swing.JTextField textfieldBateria;
    private javax.swing.JTextField textfieldBateria1;
    private javax.swing.JTextField textfieldFabricante;
    private javax.swing.JTextField textfieldFabricante1;
    private javax.swing.JTextField textfieldIdentificacion;
    private javax.swing.JTextField textfieldIdentificacion1;
    private javax.swing.JTextField textfieldModelo;
    private javax.swing.JTextField textfieldModelo1;
    private javax.swing.JTextField textfieldNumControles;
    private javax.swing.JTextField textfieldPrecio;
    private javax.swing.JTextField textfieldPrecio1;
    private javax.swing.JTextField textfieldTipoConexion;
    // End of variables declaration//GEN-END:variables
}
